BlogSite/urls.py
from cgitb import handler

from django.contrib import admin
from django.urls import path, include
from blog.urls import index
from BlogSite import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404 = "blog.views.page_not_found"
handler403 = "blog.views.forbidden"
handler500 = "blog.views.server_error"

blog/urls.py
from django.urls import path
from blog.views import (index, about, add_post, read_post,
                        update_post, delete_post, user_posts, user_info,
                        search_post, filter_post)

app_name = 'blog'
urlpatterns = [
    path('search/', search_post, name='search_post'),
    path('filter/', filter_post, name='filter_post'),
    path('about/', about, name='about'),
    path('post/<int:pk>/delete', delete_post, name='delete_post'),
    path('post/user/info/<int:user_id>/', user_info, name='user_info'),
    path('post/user/<int:user_id>/', user_posts, name='user_posts'),
    path('post/<int:pk>/edit', update_post, name='update_post'),
    path('post/<slug:slug>/', read_post, name='read_post'),
    path('post/', add_post, name='add_post'),
    path('', index, name='index'),



]

users/urls.py
from django.urls import path
from .views import (register, log_in, log_out,
                    user_profile, change_password)

app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('profile/<int:pk>', user_profile, name='profile'),
    path('change-password/', change_password, name='change_password')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from slugify import slugify
from django.urls import reverse

# Create your models here.

# описание модели поста
class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    text = models.TextField(verbose_name="Текст поста")
    created_at = models.DateTimeField(default=timezone.now,verbose_name="Дата создания", editable=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор", related_name="posts")
    image = models.ImageField(upload_to='post/', null=True, blank=True, verbose_name="Изображение")
    slug = models.SlugField(max_length=200, unique=True, editable=False, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:read_post', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post

# class PostForm(forms.Form):
#     title = forms.CharField(max_length=200, label="Заголовок")
#     text = forms.CharField(widget=forms.Textarea, label="Текст поста")
#     author = forms.ModelChoiceField(queryset=User.objects.all(), label="Автор")
#     image = forms.ImageField(required=False, label="Изображение")

class PostForm(forms.ModelForm):
    # дополняем конструктор родительского класса
    def __init__(self, *args, **kwargs):
        # получаем author из именнованных аргументов (его передали во views)
        if kwargs.get('initial'):
            author = kwargs['initial'].pop('author')
        else:
            author = kwargs.pop('author')
        # вызываем констроуктор родительского
        super().__init__(*args, **kwargs)
        # устанавливаем начальное значение поля author
        self.fields['author'].initial = author
        # отключаем видимость этого поля в форме
        self.fields['author'].diabled = True
        self.fields['author'].widget = forms.HiddenInput()

    class Meta:
        model = Post
        fields = ('title', 'text', 'image', 'author')

        labels = {
            'title': "Заголовок",
            'text': "Текст поста",
            'image': "Изображение",
            'author': "Автор"
        }

        # fields = ('title', 'text') добавляет перечисленные
        # exclude = ('author', 'created_at') все кроме перечисленных


class FilterForm(forms.Form):
    author = forms.ModelChoiceField(queryset=User.objects.all(), label='Автор')
    created_at = forms.DateField(label='Дата публикации',
                                 widget=forms.DateInput(attrs={'type': 'date'}),
                                 input_formats=["%Y-5m-%d"],
                                 required=False)

blog/views.py
from lib2to3.fixes.fix_input import context

from django.contrib.auth.decorators import login_required
from django.db.models.signals import post_delete
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from .models import Post
from .forms import PostForm, FilterForm
from django.core.paginator import Paginator

# Create your views here.


def index(request):
    # получение всех постов, отсортированных по дате публикации
    # (select * from blog_post order by created_at DESC)
    posts = Post.objects.all().order_by('-created_at')
    count_posts = Post.objects.count()            # count_posts = len(posts)
    # показываем по 3 потса на стрнице
    paginator = Paginator(posts, 3)
    # получаем номер стр из URL
    page_number = request.GET.get('page')
    # получаем обхекты для текущей стр
    page_obj = paginator.get_page(page_number)
    filter_form = FilterForm()
    context = {"title": "Главная страница",
               "page_obj": page_obj,
               "count_posts": count_posts,
               "filter_form": filter_form
    }
    return render(request, template_name='blog/index.html', context=context)

def about(request):
    count_posts = Post.objects.count()
    context = {"title": "О сайте", "count_posts": count_posts}
    return render(request, template_name='blog/about.html', context=context)

def add_post(request):
    if request.method == "GET":
        post_form = PostForm(author=request.user)
        context = {"title": "Добавить пост",'form': post_form}
        return render(request, template_name='blog/post_add.html', context=context)

    if request.method == "POST":
        post_form = PostForm(data=request.POST, files=request.FILES, author=request.user)
        if post_form.is_valid():
            # post = Post()
            # post.title = post_form.cleaned_data['title']
            # post.text = post_form.cleaned_data['text']
            # post.author = post_form.cleaned_data['author'] # request.user когда юзер зашёл под своим именем
            # post.image = post_form.cleaned_data['image']
            post_form.save()
            return index(request)

def read_post(request, slug):
   # post = Post.objects.get(pk=pk) # post = Post.objects.filter(pk=pk).first() - если несколько нужно фильтровать
    post = get_object_or_404(Post, slug=slug)
    context = {"title":"Информация о посте", "post": post}
    return render(request, template_name="blog/post_detail.html", context=context)

@login_required
def update_post(request, pk):
    #post = Post.objects.get(pk=pk)
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        post_form = PostForm(data=request.POST,
                             files=request.FILES,
                             instance=post,
                             initial={'author': post.author})
        if post_form.is_valid():
            # post.title = post_form.cleaned_data['title']
            # post.text = post_form.cleaned_data['text']
            # post.author = post_form.cleaned_data['author']  # request.user когда юзер зашёл под своим именем
            # post.image = post_form.cleaned_data['image']
            post_form.save()
            return redirect('blog:read_post', slug=post.slug)
    else:
        post_form = PostForm(initial={
            "title": post.title,
            "author": post.author,
            "text": post.text,
            "image": post.image
        })
        return render(request, template_name="blog/post_edit.html", context={"form": post_form})

@login_required
def delete_post(request, pk):
    #post = Post.objects.get(pk=pk)
    post = get_object_or_404(Post, pk=pk)
    context = {"post":post}
    if request.method == "POST":
        post.delete()
        return redirect('blog:index')
    return render(request, template_name="blog/post_delete.html", context=context)

def user_posts(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    # posts = user.posts.all()
    posts = Post.objects.filter(author=user).select_related('author')
    context = {"user":user, "posts":posts}
    return render(request, template_name='blog/user_posts.html', context=context)

@login_required
def user_info(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    context = {"user": user}
    return render(request, template_name='blog/user_info.html', context=context)


def page_not_found(request, exception):
    return render(request, template_name="blog/404.html", context={"title": "404"})

def forbidden(request, exception):
    return render(request, template_name="blog/403.html", context={"title": "403"})

def server_error(request):
    return render(request, template_name="blog/500.html", context={"title": "500"})

def search_post(request):
    query = request.GET.get('query')
    query_text = Q(title__icontains=query) | Q(text__icontains=query)
    results = Post.objects.filter(query_text)
    paginator = Paginator(results, 3)
    # получаем номер стр из URL
    page_number = request.GET.get('page')
    # получаем объекты для текущей стр
    page_obj = paginator.get_page(page_number)
    count_posts = results.count()
    context = {"title": "Главная страница",
               "page_obj": page_obj,
               "count_posts": count_posts
    }
    return render(request, template_name='blog/index.html', context=context)

def filter_post(request):
    author_id = request.GET.get('author')
    if not author_id:
        results = Post.objects.all()
    author = User.objects.get(pk=author_id)
    query_text = Q(author__exact=author)
    results = Post.objects.filter(query_text)

    paginator = Paginator(results, 3)
    # получаем номер стр из URL
    page_number = request.GET.get('page')
    # получаем объекты для текущей стр
    page_obj = paginator.get_page(page_number)
    count_posts = results.count()
    filter_form = FilterForm()
    context = {"title": "Главная страница",
               "page_obj": page_obj,
               "count_posts": count_posts,
               "filter_form": filter_form
               }
    return render(request, template_name='blog/index.html', context=context)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>О сайте </h2>
<p>Автор - {{name}} {{lastname}}</p>
<p>Эл. Почта - {{email}}</p>

<h3>
    На сайте нашего блога <span><b>{{count_posts}}</b></span> постов.
</h3>


{% endblock content %}

blog/templates/blog/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <title>{{title}}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js">
</head>
<body>
<nav class="nav">
  <a class="nav-link active" aria-current="page" href="{% url 'blog'}"></a>

</nav>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'blog:index' %}">Главная</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'blog:add_post' %}">Добавить пост</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:about' %}">О сайте</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            ...
          </a>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Аккаунт
          </a>
          <ul class="dropdown-menu">
            {% if not user.is_authenticated %}
              <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
              <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
              <li><hr class="dropdown-divider"></li>
            {% endif %}
            {% if user.is_authenticated %}
              <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
              <li><a class="dropdown-item" href="{% url 'users:profile' pk=user.pk %}">{{ user.username }}</a></li>
            {% endif %}
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% if messages %}
    {% for message in messages %}
      <div>{{ message }}</div>
    {% endfor %}
{% endif %}

{% block content %}
{% endblock content %}
</body>
</html>

blog/templates/blog/index.html
    {% extends 'blog/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}

<div>
    <form action="{% url 'blog:search_post' %}" method="get" style="display: flex; margin-right: 50px;">
        <input type="search" name="query">
        <button type="submit">Поиск</button>
    </form>
</div>

<div>
    <form action="{% url 'blog:filter_post' %}" method="get" style="display: flex; margin-right: 50px;">
        <input type="search" name="query">
        <button type="submit">Фильтровать</button>
    </form>
</div>

<div>
    <form action="" method="get" style="display: flex; margin-right: 50 px">
        {{ filter_form.author }}
        {{ filter_form.created_at }}
        <button type="submit">Фильтровать</button>
    </form>
</div>

{% if page_obj|length == 0 %}
<h2>По вашему запросу ничего не найдено</h2>
{% else %}
    <img src="{% static 'img/sunset.jpg '%}" width="400" height="auto">

    <h1>Главная страница</h1>

    <div class="post-list">
        {% for post in page_obj %}
            <div class="post-image">
            <h3><b>{{ post.author }}</b></h3>
                {% if post.image %}
                    <img src="{{ post.image.url }}" width="200px" height="auto">
                {% else %}
                    <img src="{% static 'img/no.jpg'%}" width="150px" height="auto">
                {% endif %}
            </div>
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            <p>{{ post.text }}</p>
            <p><i>{{ post.created_at }}</i></p>
        {% endfor %}
    </div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="/?page=1">&laquo;Первая</a>
                <a href="/?page={{ page_obj.previous_page_number }}">Предыдущая</a>
            {% endif %}
            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
                <a href="?{% url_replace request 'page' page_obj.next_page_number %}">Следующая</a>
                <a href="/?page={{ page_obj.paginator.num_pages }}">Последняя&raquo;</a>
            {% endif %}
        </span>
    </div>
{% endif %}

{% endblock content %}

blog/templates/blog/post_add.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>Добавить новый пост</h1>

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить пост</button>

</form>

{% endblock content %}

blog/templates/blog/post_delete.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>Удаление поста</h1>
<p>Автор - {{ post.author }}</p>
<p>Заголовок - {{ post.title }}</p>

<form method="post">
    {% csrf_token %}
    <button type="submit">Удалить пост</button>
    <a href="{% url 'blog:index' %}">
        <button type="button">Отменить</button>
    </a>
</form>

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
<h1>Информация о посте № {{ post.pk }}</h1>

<hr>
{% if user.is_authenticated %}
<a href="{% url 'blog:user_info' user_id=post.author.pk %}">
    {{ post.author }}
</a>
{% else %}
    {{ post.author }}
{% endif %}

<h3>{{ post.title }}</h3>

{% if post.image %}
<p><img src="{{ post.image.url }}" width="400px" height="auto"></p>
{% else %}
<p><img src="{% static 'img/no.jpg'%}" width="150px" height="auto"></p>
{% endif %}

{{ post.text }}
<p><i>{{ post.created_at }}</i></p>

{% if user == post.author  %}
    <div class="btn-actions">
        <div class="btn-edit-post">
            <a href="{% url 'blog:update_post' pk=post.id %}">
                <button type="button">Редактировать</button>
            </a>
        </div>
        <div class="btn-del-post">
            <a href="{% url 'blog:delete_post' pk=post.id %}">
                <button type="button">Удалить</button>
            </a>
        </div>
    </div>
{% endif %}
{% if user == post.author %}
        <div class="btn-actions">
            <div class="btn-edit-post">
                <a href="{% url 'blog:update_post' pk=post.id %}">
                <button type="button">Редактировать</button>
                </a>
            </div>
        </div>
    {% else %}
        {% if user.is_superuser %}
            <div class="btn-actions">
                <div class="btn-del-post">
                    <a href="{% url 'blog:delete_post' pk=post.id %}">
                        <button type="button">Удалить</button>
                    </a>
                </div>
            </div>
    {% endif %}
{% endif %}

{% endblock content %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>Редактировать пост</h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Изменить пост</button>

</form>

{% endblock content %}

blog/templates/blog/posts.html
{% extends 'blog/base.html' %}

{% block content %}
<h2>Список постов</h2>
{% for post in page_obj %}
    <h2>{{post.author}}: <a href="{{ post.get_absolute_url }}">{{post.title}}</a></h2>
    <p>{{post.text}}</p>
    <p>{{post.created_at}}</p>
    <br>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo;Первая</a>
            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Последняя&raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock content %}

blog/templates/blog/user_posts.html
{% extends 'blog/base.html' %}

{% block content %}

{% if user == request.user %}
  <h3>Мои посты</h3>
{% else %}
  <h1>Посты пользователя {{user.username }} </h1>
{% endif %}

<div class="post-list">
    {% for post in page_obj %}
        <div class="post-image">
        <h3><b>{{ post.author }}</b></h3>
            {% if post.image %}
                <img src="{{ post.image.url }}" width="200px" height="auto">
            {% else %}
                <img src="{% static 'img/no.jpg'%}" width="150px" height="auto">
            {% endif %}
        </div>
        <div class="post-author">
        <h3><b>{{ post.author }}</b></h3>
        </div>
        <div class="post-title">
          <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        <p>{{ post.text }}</p>
        <p><i>{{ post.created_at }}</i></p>
          </div>
    {% endfor %}
</div>

{% endblock content %}